---
# tasks file for kostyrevaa.openswan

- name: install basics packages
  package:
    name: '{ item }'
    state: present

  with_items:
    - libnss3-dev
    - libnspr4-dev
    - pkg-config
    - libpam0g-dev
    - libcap-ng-dev
    - libcap-ng-utils
    - libselinux1-dev
    - libcurl4-nss-dev
    - flex
    - bison
    - gcc
    - make
    - libunbound-dev
    - libnss3-tools
    - libevent-dev
    - libgmp3-dev

- name: get openswan
  shell: >-
    wget https://download.openswan.org/openswan/{{ openswan_tarball }}
    chdir=/tmp
    creates=/tmp/{{ openswan_tarball }}
                    
- name: unarchive
  unarchive: >-
    copy=no
    src=/tmp/{{ openswan_tarball }}
    dest=/tmp/
    creates=/tmp/{{ openswan_src_dir }}
    
- name: setup Makefile
  copy: >-  
    dest=/tmp/{{ openswan_src_dir }}/Makefile.inc.local
    src={{ openswan_makefile_path }}

- name: make install
  shell: make -s programs && make -s install chdir=/tmp/{{ openswan_src_dir }}
    
- name: render template /etc/ipsec.conf
  template:
    src: ipsec.conf.j2
    dest: /etc/ipsec.conf
    owner: root
    group: root
    mode: '0600'
  notify: restart ipsec service
  tags: config

- name: render /etc/ipsec.d/{{ item.key | regex_replace('%','') }}.conf
  template:
    src: conn.j2
    dest: "/etc/ipsec.d/{{ item.key | regex_replace('%','') }}.conf"
    owner: root
    group: root
    mode: '0600'
  with_dict: "{{ openswan_connections }}"
  notify: restart ipsec service
  tags:
    - config
    - conn

- name: make sure /etc/ipsec.secrets includes other secrets
  copy:
    content: "include ipsec.d/*.secrets\n"
    dest: /etc/ipsec.secrets
    owner: root
    group: root
    mode: '0600'

- name: render /etc/ipsec.d/{{ item.key }}.secrets
  template:
    src: secrets.j2
    dest: "/etc/ipsec.d/{{ item.key }}.secrets"
    owner: root
    group: root
    mode: '0600'
  with_dict: "{{ openswan_connections }}"
  when:
    - openswan_manage_secrets
    - item.value.psk_string is defined
  notify: restart ipsec service
  tags:
    - config
    - secrets

- name: enable and start ipsec service
  service:
    name: ipsec
    state: started
    enabled: yes
  when: openswan_manage_service
